// ============================================================
// questions.js — Banque de questions — Maths 5ème
// Auteur du cours : ADRIEN KONAN
// ============================================================

const LESSONS = [
  { id: 1, title: "Puissance entière d'un nombre entier naturel", competence: "Calcul & Algèbre" },
  { id: 2, title: "Nombres premiers", competence: "Arithmétique" },
  { id: 3, title: "Figures symétriques par rapport à une droite", competence: "Géométrie" },
  { id: 4, title: "Angles", competence: "Géométrie" },
  { id: 5, title: "Nombres décimaux relatifs", competence: "Nombres & Calcul" },
  { id: 6, title: "Segments — Caractérisation & Médiatrice", competence: "Géométrie" },
  { id: 7, title: "Fractions", competence: "Calcul & Fractions" },
  { id: 8, title: "Triangles", competence: "Géométrie" },
  { id: 9, title: "Cercles et disques", competence: "Géométrie" },
  { id: 10, title: "Parallélogrammes particuliers, Proportionnalité & Statistiques", competence: "Géométrie & Données" },
];

const COURSE_PARTS = {
  1: {
    "definition_puissance": { label: "1.1 Définition de la puissance aⁿ", icon: "📖" },
    "regles_priorite":      { label: "1.2a Règles de priorité des opérations", icon: "📐" },
    "regle1_produit":       { label: "1.2b Règle 1 : aᵐ⁺ⁿ = aᵐ × aⁿ", icon: "📐" },
    "regle2_produit":       { label: "1.2b Règle 2 : aⁿ × bⁿ = (a×b)ⁿ", icon: "📐" },
  },
  2: {
    "division_euclidienne": { label: "2.1 Division euclidienne dans ℕ", icon: "📖" },
    "def_premier":          { label: "2.2a Définition d'un nombre premier", icon: "📖" },
    "reconnaitre_premier":  { label: "2.2b Règle pour reconnaître un nombre premier", icon: "📐" },
    "decomposition":        { label: "2.2c Décomposition en produit de facteurs premiers", icon: "📐" },
  },
  3: {
    "def_symetrique":       { label: "1. Points symétriques par rapport à une droite", icon: "📖" },
    "prop_alignes":         { label: "2.1 Symétriques de points alignés", icon: "📐" },
    "symetrie_droite":      { label: "2.2 Symétrique d'une droite par rapport à une droite", icon: "📐" },
    "symetrie_segment":     { label: "2.3 Symétrique d'un segment par rapport à une droite", icon: "📐" },
    "axe_symetrie":         { label: "3. Axe de symétrie d'une figure", icon: "📖" },
  },
  4: {
    "presentation_angles":  { label: "1.1 Présentation des angles (vocabulaire, mesure)", icon: "📖" },
    "angles_adj":           { label: "1.2 Angles adjacents", icon: "📐" },
    "compl_suppl":          { label: "2. Angles complémentaires et supplémentaires", icon: "📐" },
    "angles_ops":           { label: "3. Angles opposés par le sommet", icon: "📐" },
    "somme_triangle":       { label: "4. Somme des mesures des angles d'un triangle", icon: "📐" },
  },
  5: {
    "ensemble_relatifs":    { label: "1.1 Ensemble des nombres décimaux relatifs (ℤ)", icon: "📖" },
    "ordre_relatifs":       { label: "1.2 Ordre des nombres décimaux relatifs", icon: "📐" },
    "somme_relatifs":       { label: "3.1 Somme de deux nombres décimaux relatifs", icon: "📐" },
    "difference_relatifs":  { label: "3.2 Différence de deux nombres décimaux relatifs", icon: "📐" },
    "produit_relatifs":     { label: "5.2 Produit de nombres décimaux relatifs", icon: "📐" },
    "equation_relatifs":    { label: "4. Équation du type x + a = b", icon: "📐" },
  },
  6: {
    "carac_segment":        { label: "1.1 Caractérisation d'un segment (AM + MB = AB)", icon: "📖" },
    "reciproque_segment":   { label: "1.2 Propriété réciproque du segment", icon: "📐" },
    "carac_mediatrice":     { label: "2.1 Caractérisation de la médiatrice (MA = MB)", icon: "📖" },
    "reciproque_mediatrice":{ label: "2.2 Propriété réciproque de la médiatrice", icon: "📐" },
  },
  7: {
    "somme_meme_denom":     { label: "1.1 Somme/Différence de fractions (même dénominateur)", icon: "📖" },
    "somme_diff_denom":     { label: "1.2 Somme/Différence de fractions (dénominateurs différents)", icon: "📐" },
    "produit_fraction":     { label: "2. Produit de deux fractions", icon: "📐" },
    "puissance_fraction":   { label: "3. Puissance entière d'une fraction", icon: "📐" },
    "encadrement_fraction": { label: "4. Encadrement d'une fraction par des décimaux", icon: "📖" },
  },
  8: {
    "triangle_vocab":       { label: "1. Triangle — vocabulaire et construction", icon: "📖" },
    "triangle_isocele":     { label: "2.1 Triangle isocèle — définition et propriétés", icon: "📐" },
    "triangle_equilateral": { label: "2.2 Triangle équilatéral — définition et propriétés", icon: "📐" },
    "triangle_rectangle":   { label: "2.3 Triangle rectangle — définition et propriétés", icon: "📐" },
    "droites_particulieres":{ label: "3. Droites particulières d'un triangle", icon: "📐" },
    "inegalites_triangul":  { label: "4. Inégalités triangulaires", icon: "📐" },
  },
  9: {
    "cercle_disque":        { label: "1. Cercle et disque — présentation et notation", icon: "📖" },
    "positions_cercle":     { label: "2. Positions d'un point par rapport à un cercle", icon: "📐" },
    "carac_disque":         { label: "3. Caractérisation du disque", icon: "📖" },
    "cercle_circonscrit":   { label: "4. Cercle circonscrit à un triangle", icon: "📐" },
    "cercle_inscrit":       { label: "5. Cercle inscrit dans un triangle", icon: "📐" },
  },
  10: {
    "parallelogramme":      { label: "1. Parallélogramme — définition et propriétés", icon: "📐" },
    "rectangle":            { label: "2.1 Rectangle — définition et propriétés", icon: "📐" },
    "losange":              { label: "2.2 Losange — définition et propriétés", icon: "📐" },
    "carre":                { label: "2.3 Carré — définition et propriétés", icon: "📐" },
    "statistiques":         { label: "Statistiques — Population, effectifs et fréquences", icon: "📊" },
    "prismes":              { label: "Prismes droits — définition, aires et volumes", icon: "📖" },
  },
};

const QUESTION_BANK = {

  // ─────────────────────────────────────────────────
  // LEÇON 1 — Puissance entière d'un nombre entier naturel
  // ─────────────────────────────────────────────────
  1: [
    { q: "Qu'est-ce que désigne aⁿ ?", opts: ["La somme de n facteurs a", "Le produit de n facteurs égaux à a", "La racine carrée de a", "a divisé par n"], ans: 1, expl: "aⁿ désigne le produit de n facteurs égaux à a : aⁿ = a × a × … × a (n facteurs).", part: "definition_puissance" },
    { q: "Comment se lit 3⁵ ?", opts: ["3 fois 5", "3 puissance 5 ou 3 exposant 5", "5 exposant 3", "15"], ans: 1, expl: "3⁵ se lit « 3 exposant 5 » ou « 3 puissance 5 ». C'est 3 × 3 × 3 × 3 × 3 = 243.", part: "definition_puissance" },
    { q: "Calcule 2⁵.", opts: ["10", "16", "32", "64"], ans: 2, expl: "2⁵ = 2 × 2 × 2 × 2 × 2 = 32.", part: "definition_puissance" },
    { q: "Quelle est la valeur de a⁰ pour a ≠ 0 ?", opts: ["0", "a", "1", "Indéfini"], ans: 2, expl: "Par convention, a⁰ = 1 pour tout a ≠ 0.", part: "definition_puissance" },
    { q: "Comment s'écrit 7 × 7 sous forme de puissance ?", opts: ["7²", "2⁷", "7 + 7", "14"], ans: 0, expl: "7 × 7 = 7² (7 au carré). Le produit de 2 facteurs égaux à 7.", part: "definition_puissance" },
    { q: "Calcule 4².", opts: ["8", "16", "12", "6"], ans: 1, expl: "4² = 4 × 4 = 16. Le carré de 4 est 16.", part: "definition_puissance" },
    { q: "5 × 5 × 5 s'écrit sous forme de puissance :", opts: ["3⁵", "5³", "5 × 3", "15"], ans: 1, expl: "5 × 5 × 5 = 5³ (5 au cube). Il y a 3 facteurs égaux à 5.", part: "definition_puissance" },
    { q: "Dans l'expression 4³, quel est l'exposant ?", opts: ["4", "3", "12", "64"], ans: 1, expl: "Dans aⁿ, n est l'exposant. Dans 4³, l'exposant est 3.", part: "definition_puissance" },
    { q: "Dans une suite d'opérations sans parenthèses, que calcule-t-on en premier ?", opts: ["L'addition", "La soustraction", "La multiplication", "Les puissances"], ans: 3, expl: "Les puissances sont prioritaires sur ×, + et −. Puis vient la multiplication avant + et −.", part: "regles_priorite" },
    { q: "Calcule 7 + 8 × 4.", opts: ["60", "39", "15", "120"], ans: 1, expl: "Multiplication prioritaire : 8 × 4 = 32, puis 7 + 32 = 39.", part: "regles_priorite" },
    { q: "Calcule 5 × 2³.", opts: ["1000", "40", "15", "125"], ans: 1, expl: "Puissance d'abord : 2³ = 8, puis 5 × 8 = 40.", part: "regles_priorite" },
    { q: "Calcule 4² × 5 + 9.", opts: ["1025", "69", "89", "25"], ans: 2, expl: "4² = 16, puis 16 × 5 = 80, puis 80 + 9 = 89.", part: "regles_priorite" },
    { q: "Calcule (2 + 3) × 4.", opts: ["14", "20", "24", "11"], ans: 1, expl: "Parenthèses d'abord : (2 + 3) = 5, puis 5 × 4 = 20.", part: "regles_priorite" },
    { q: "Que vaut 7³ × 7² selon la règle aᵐ × aⁿ = aᵐ⁺ⁿ ?", opts: ["7¹", "7⁶", "7⁵", "49⁵"], ans: 2, expl: "7³ × 7² = 7³⁺² = 7⁵. On additionne les exposants quand la base est la même.", part: "regle1_produit" },
    { q: "5¹⁷ s'écrit comme :", opts: ["5¹⁰ + 5⁷", "5¹⁰ × 5⁷", "5¹⁰ − 5⁷", "5¹⁰ ÷ 5⁷"], ans: 1, expl: "5¹⁷ = 5¹⁰⁺⁷ = 5¹⁰ × 5⁷ selon la règle aᵐ⁺ⁿ = aᵐ × aⁿ.", part: "regle1_produit" },
    { q: "Complète : b? × b² = b⁸", opts: ["b³", "b⁶", "b⁴", "b¹⁰"], ans: 1, expl: "b? × b² = b⁸ → ? + 2 = 8 → ? = 6. Donc b⁶ × b² = b⁸.", part: "regle1_produit" },
    { q: "Selon la règle aⁿ × bⁿ = (a × b)ⁿ, que vaut 2³ × 5³ ?", opts: ["10⁶", "10³", "7³", "2⁵ × 5²"], ans: 1, expl: "2³ × 5³ = (2 × 5)³ = 10³ = 1000.", part: "regle2_produit" },
    { q: "3⁴ × 2⁴ est égal à :", opts: ["6⁸", "5⁴", "6⁴", "12⁴"], ans: 2, expl: "3⁴ × 2⁴ = (3 × 2)⁴ = 6⁴ selon la règle aⁿ × bⁿ = (a × b)ⁿ.", part: "regle2_produit" },
    { q: "Complète : (…… × ……)² = 15²", opts: ["3 × 5", "7 × 8", "5 × 10", "6 × 9"], ans: 0, expl: "(3 × 5)² = 15² car 3 × 5 = 15. La règle aⁿ × bⁿ = (a × b)ⁿ s'inverse.", part: "regle2_produit" },
    { q: "Calcule 3³.", opts: ["9", "18", "27", "81"], ans: 2, expl: "3³ = 3 × 3 × 3 = 9 × 3 = 27.", part: "definition_puissance" },
    { q: "Quelle est la valeur de 10² ?", opts: ["20", "100", "1000", "12"], ans: 1, expl: "10² = 10 × 10 = 100.", part: "definition_puissance" },
    { q: "Calcule 3 + 4².", opts: ["49", "19", "48", "144"], ans: 1, expl: "Puissance d'abord : 4² = 16, puis 3 + 16 = 19.", part: "regles_priorite" },
    { q: "Complète : 6⁹ × 6 = 6…", opts: ["6⁸", "6⁵⁴", "6¹⁰", "36⁹"], ans: 2, expl: "6⁹ × 6 = 6⁹ × 6¹ = 6⁹⁺¹ = 6¹⁰.", part: "regle1_produit" },
    { q: "a⁴ × a² × a³ = ?", opts: ["a⁹", "a²⁴", "a¹⁴", "3a⁹"], ans: 0, expl: "a⁴ × a² × a³ = a⁴⁺²⁺³ = a⁹.", part: "regle1_produit" },
    { q: "100 000 peut s'écrire :", opts: ["10⁵", "10⁶", "10⁷", "5¹⁰"], ans: 0, expl: "100 000 = 10 × 10 × 10 × 10 × 10 = 10⁵.", part: "definition_puissance" },
    { q: "Calcule (3 × 2)².", opts: ["12", "18", "36", "30"], ans: 2, expl: "(3 × 2)² = 6² = 36.", part: "regles_priorite" },
    { q: "11⁴ peut s'écrire aussi :", opts: ["11³ × 11¹", "11² + 11²", "4¹¹", "11 × 4"], ans: 0, expl: "11⁴ = 11³⁺¹ = 11³ × 11¹, selon aᵐ⁺ⁿ = aᵐ × aⁿ.", part: "regle1_produit" },
    { q: "Calcule 33 – (1 + 3)².", opts: ["17", "29", "33", "16"], ans: 0, expl: "Parenthèses : 1 + 3 = 4, puis 4² = 16, enfin 33 – 16 = 17.", part: "regles_priorite" },
    { q: "30⁴ peut s'écrire sous la forme (a × b × c)⁴. Laquelle est correcte ?", opts: ["(3 × 1 × 0)⁴", "(3 × 2 × 5)⁴", "(6 × 5)⁴", "(2 × 15)⁴"], ans: 1, expl: "30 = 2 × 3 × 5 donc 30⁴ = (2 × 3 × 5)⁴.", part: "regle2_produit" },
    { q: "Koffi calcule 5² × 3 + 4. Quel est le bon résultat ?", opts: ["25", "79", "34", "179"], ans: 1, expl: "5² = 25, puis 25 × 3 = 75, puis 75 + 4 = 79.", part: "regles_priorite" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 2 — Nombres premiers
  // ─────────────────────────────────────────────────
  2: [
    { q: "Dans la division euclidienne a = b × q + r, quel est r ?", opts: ["Le dividende", "Le diviseur", "Le quotient", "Le reste"], ans: 3, expl: "a = b × q + r : a = dividende, b = diviseur, q = quotient, r = reste.", part: "division_euclidienne" },
    { q: "Dans la division euclidienne, le reste est toujours :", opts: ["Supérieur au diviseur", "Égal au diviseur", "Inférieur au diviseur", "Nul"], ans: 2, expl: "Le reste r vérifie toujours 0 ≤ r < b (r < diviseur).", part: "division_euclidienne" },
    { q: "On donne 267 = 13 × 20 + 7. Quel est le reste de la division de 267 par 13 ?", opts: ["13", "20", "7", "267"], ans: 2, expl: "Dans a = b × q + r, 267 = 13 × 20 + 7, donc le reste est 7.", part: "division_euclidienne" },
    { q: "Si a est un multiple de b, alors le reste est :", opts: ["1", "b", "a", "0"], ans: 3, expl: "Si a est multiple de b, alors a = b × q + 0, donc le reste est nul.", part: "division_euclidienne" },
    { q: "On a 20 = 3 × 6 + 2. L'encadrement de 20 par deux multiples consécutifs de 3 est :", opts: ["15 < 20 < 18", "18 < 20 < 21", "18 < 20 < 24", "12 < 20 < 15"], ans: 1, expl: "3 × 6 = 18 < 20 < 3 × 7 = 21. Donc 18 < 20 < 21.", part: "division_euclidienne" },
    { q: "Qu'est-ce qu'un nombre premier ?", opts: ["Un nombre pair > 2", "Un entier naturel qui a exactement 2 diviseurs : 1 et lui-même", "Un entier divisible par 1 seulement", "Un nombre impair quelconque"], ans: 1, expl: "Un nombre premier est un entier naturel non nul qui admet exactement deux diviseurs : 1 et lui-même.", part: "def_premier" },
    { q: "Parmi ces nombres, lequel est premier ?", opts: ["1", "4", "9", "7"], ans: 3, expl: "7 est premier car ses seuls diviseurs sont 1 et 7. 1 n'est pas premier (1 diviseur). 4 et 9 ont d'autres diviseurs.", part: "def_premier" },
    { q: "Pourquoi 6 n'est-il pas un nombre premier ?", opts: ["Car il est pair", "Car ses diviseurs sont 1, 2, 3 et 6 (plus de 2 diviseurs)", "Car il est inférieur à 10", "Car il n'est pas impair"], ans: 1, expl: "6 a 4 diviseurs : 1, 2, 3, 6. Un nombre premier n'en a que 2.", part: "def_premier" },
    { q: "Le nombre 1 est-il un nombre premier ?", opts: ["Oui, car il est impair", "Non, car il n'a qu'un seul diviseur", "Oui, car il est plus petit que 2", "Non, car il est pair"], ans: 1, expl: "1 n'est pas premier : il n'a qu'un seul diviseur (lui-même). Un nombre premier en a exactement 2.", part: "def_premier" },
    { q: "Quelle est la liste des 5 premiers nombres premiers ?", opts: ["1, 3, 5, 7, 9", "2, 3, 5, 7, 11", "2, 4, 6, 8, 10", "1, 2, 3, 5, 7"], ans: 1, expl: "Les 5 premiers nombres premiers sont : 2, 3, 5, 7, 11.", part: "def_premier" },
    { q: "Le seul nombre premier pair est :", opts: ["4", "6", "2", "8"], ans: 2, expl: "2 est le seul nombre premier pair. Tous les autres nombres pairs sont divisibles par 2.", part: "def_premier" },
    { q: "Pour savoir si 51 est premier, on le divise d'abord par :", opts: ["51", "10", "2", "51 ÷ 2"], ans: 2, expl: "On divise par les nombres premiers dans l'ordre croissant, en commençant par 2.", part: "reconnaitre_premier" },
    { q: "51 est-il un nombre premier ? (51 = 3 × 17)", opts: ["Oui", "Non, car 51 = 3 × 17", "Oui, car il est impair", "On ne peut pas savoir"], ans: 1, expl: "51 = 3 × 17, donc 51 a plus de 2 diviseurs (1, 3, 17 et 51). Il n'est pas premier.", part: "reconnaitre_premier" },
    { q: "Pour montrer que 41 est premier, on vérifie que :", opts: ["41 est divisible par 2", "Aucun nombre premier ≤ √41 ne divise 41", "41 est impair", "41 se termine par 1"], ans: 1, expl: "On divise 41 par 2, 3, 5, 7 successivement. Comme 7 > quotient, 41 est premier.", part: "reconnaitre_premier" },
    { q: "On cherche si 67 est premier. On trouve 67 = 7 × 9 + 4. Comme le quotient 9 < 7 est faux, que conclut-on ?", opts: ["67 est premier", "67 n'est pas premier", "Il faut continuer avec 11", "On ne sait pas"], ans: 0, expl: "Quand le quotient est inférieur ou égal au diviseur utilisé, le nombre est premier.", part: "reconnaitre_premier" },
    { q: "La décomposition de 12 en produit de facteurs premiers est :", opts: ["4 × 3", "2² × 3", "2 × 6", "3 × 4"], ans: 1, expl: "12 = 2 × 2 × 3 = 2² × 3. Les facteurs doivent être des nombres premiers.", part: "decomposition" },
    { q: "La décomposition de 36 en produit de facteurs premiers est :", opts: ["4 × 9", "6²", "2² × 3²", "2³ × 3"], ans: 2, expl: "36 = 2 × 2 × 3 × 3 = 2² × 3².", part: "decomposition" },
    { q: "La décomposition de 45 en produit de facteurs premiers est :", opts: ["9 × 5", "3² × 5", "3 × 15", "5² × 3"], ans: 1, expl: "45 = 3 × 3 × 5 = 3² × 5.", part: "decomposition" },
    { q: "Lors d'une décomposition en produit de facteurs premiers, on divise par des nombres :", opts: ["Pairs seulement", "Premiers dans l'ordre croissant", "Au hasard", "Impairs seulement"], ans: 1, expl: "On divise par les nombres premiers 2, 3, 5, 7, 11… dans l'ordre croissant.", part: "decomposition" },
    { q: "La décomposition de 324 en produit de facteurs premiers est :", opts: ["2² × 3⁴", "2³ × 3³", "4 × 12", "2 × 162"], ans: 0, expl: "324 = 2 × 162 = 2 × 2 × 81 = 4 × 81 = 2² × 3⁴.", part: "decomposition" },
    { q: "2⁵ × 7³ × 11 est-elle une décomposition en produit de facteurs premiers ?", opts: ["Non, car 2, 7 et 11 ne sont pas premiers", "Oui, car 2, 7 et 11 sont des nombres premiers", "Non, car les exposants sont différents", "On ne peut pas savoir"], ans: 1, expl: "2, 7 et 11 sont tous des nombres premiers, donc c'est bien une décomposition valide.", part: "decomposition" },
    { q: "32 × 5³ × 6 est-elle une décomposition en produit de facteurs premiers ?", opts: ["Oui", "Non, car 6 n'est pas un nombre premier", "Non, car 3 n'est pas premier", "Oui, si on considère 6 comme premier"], ans: 1, expl: "6 = 2 × 3 n'est pas un nombre premier. La décomposition valide serait 2² × 3 × 5³.", part: "decomposition" },
    { q: "La division euclidienne de 53 par 7 est traduite par :", opts: ["53 = 7 × 8 + 2", "53 = 7 × 7 + 4", "53 = 8 × 7 − 3", "53 = 7 × 9 − 10"], ans: 1, expl: "7 × 7 = 49, 53 − 49 = 4. Donc 53 = 7 × 7 + 4. On vérifie : 4 < 7 ✓.", part: "division_euclidienne" },
    { q: "L'égalité 33 = 5 × 4 + 13 traduit-elle la division euclidienne de 33 par 5 ?", opts: ["Oui", "Non, car 13 > 5 (le reste doit être inférieur au diviseur)", "Oui, si on admet que 13 < 33", "On ne peut pas savoir"], ans: 1, expl: "Le reste 13 doit être strictement inférieur au diviseur 5. Or 13 > 5, donc ce n'est pas valide.", part: "division_euclidienne" },
    { q: "Parmi ces listes, laquelle contient uniquement des nombres premiers ?", opts: ["1, 5, 11, 23", "2, 7, 13, 19", "0, 3, 17, 37", "2, 43, 57, 61"], ans: 1, expl: "2, 7, 13, 19 sont tous premiers. 1 n'est pas premier, 0 n'est pas premier, 57 = 3 × 19.", part: "def_premier" },
    { q: "La décomposition de 224 en produit de facteurs premiers est :", opts: ["2⁴ × 7", "2³ × 4 × 7", "2⁵ × 7", "4 × 56"], ans: 2, expl: "224 = 2 × 112 = 2 × 2 × 56 = 4 × 56 = 4 × 4 × 14 = 2⁵ × 7.", part: "decomposition" },
    { q: "Qu'est-ce que l'encadrement de 267 par deux multiples consécutifs de 13 (267 = 13 × 20 + 7) ?", opts: ["250 < 267 < 260", "260 < 267 < 273", "261 < 267 < 274", "13 × 19 < 267 < 13 × 21"], ans: 1, expl: "13 × 20 = 260 < 267 < 13 × 21 = 273.", part: "division_euclidienne" },
    { q: "Quelle est la valeur de 20¹⁹⁰ (exposant = 190 en puissance quelconque non nulle) si 20190 = ?", opts: ["1", "20", "190", "0"], ans: 0, expl: "2019⁰ = 1. Tout nombre (non nul) à la puissance 0 vaut 1.", part: "def_premier" },
    { q: "Quel est le quotient de la division euclidienne de 69 par 12 ?", opts: ["5", "6", "7", "4"], ans: 0, expl: "12 × 5 = 60, 69 − 60 = 9. Donc 69 = 12 × 5 + 9. Le quotient est 5.", part: "division_euclidienne" },
    { q: "La décomposition de 2350 en produit de facteurs premiers est :", opts: ["2 × 5² × 47", "2 × 5 × 235", "5² × 94", "2² × 5 × 47"], ans: 0, expl: "2350 = 2 × 1175 = 2 × 5 × 235 = 2 × 5 × 5 × 47 = 2 × 5² × 47.", part: "decomposition" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 3 — Figures symétriques par rapport à une droite
  // ─────────────────────────────────────────────────
  3: [
    { q: "A et A' sont symétriques par rapport à (D) signifie que :", opts: ["(D) passe par A", "(D) est la médiatrice de [AA']", "(D) est parallèle à [AA']", "A et A' sont sur (D)"], ans: 1, expl: "A et A' sont symétriques par rapport à (D) signifie que (D) est la médiatrice du segment [AA'].", part: "def_symetrique" },
    { q: "Si M appartient à la droite (D), quel est son symétrique par rapport à (D) ?", opts: ["Il n'existe pas", "Le point diamétralement opposé", "M lui-même", "Le pied de la perpendiculaire"], ans: 2, expl: "Chaque point M de la droite (D) est son propre symétrique par rapport à (D).", part: "def_symetrique" },
    { q: "Pour construire le symétrique d'un point A par rapport à (D), on trace :", opts: ["La parallèle à (D) par A", "La perpendiculaire à (D) par A, puis on reporte la distance", "Un cercle de centre A", "Une droite quelconque par A"], ans: 1, expl: "On trace la perpendiculaire à (D) passant par A, puis on reporte la même distance de l'autre côté.", part: "def_symetrique" },
    { q: "Si A et A' sont symétriques par rapport à (D), que vaut AI où I est le pied de la perpendiculaire depuis A ?", opts: ["AI = 2 × A'I", "AI = A'I", "AI > A'I", "AI < A'I"], ans: 1, expl: "(D) est la médiatrice de [AA'], donc I est le milieu de [AA'] : AI = A'I.", part: "def_symetrique" },
    { q: "Des points A, B, C sont alignés. Leurs symétriques A', B', C' par rapport à (D) sont :", opts: ["En triangle", "Non alignés en général", "Alignés", "Sur la droite (D)"], ans: 2, expl: "Propriété 1 : Lorsque des points sont alignés, leurs symétriques par rapport à une droite sont aussi alignés.", part: "prop_alignes" },
    { q: "Les symétriques de deux droites parallèles par rapport à une droite sont :", opts: ["Perpendiculaires", "Concourantes", "Parallèles", "Confondues"], ans: 2, expl: "Les symétriques de deux droites parallèles par rapport à une droite sont également parallèles.", part: "prop_alignes" },
    { q: "Si (D) est perpendiculaire à une droite (L), le symétrique de (L) par rapport à (D) est :", opts: ["Une droite parallèle à (L)", "La droite (L) elle-même", "Une droite perpendiculaire à (D)", "Une droite oblique"], ans: 1, expl: "Si (D) ⊥ (L), la droite (L) est son propre symétrique par rapport à (D).", part: "symetrie_droite" },
    { q: "Pour construire le symétrique d'une droite (L) par rapport à (D), il faut :", opts: ["Trouver les symétriques de deux points de (L)", "Tracer une parallèle à (L)", "Mesurer les angles", "Utiliser un compas uniquement"], ans: 0, expl: "On construit les symétriques de deux points de (L), puis on trace la droite passant par ces deux symétriques.", part: "symetrie_droite" },
    { q: "Le symétrique d'un segment par rapport à une droite est :", opts: ["Un segment de longueur double", "Un segment de même longueur", "Un point", "Une droite"], ans: 1, expl: "Propriété 3 : Le symétrique d'un segment par rapport à une droite est un segment de même longueur.", part: "symetrie_segment" },
    { q: "Si [AB] et [A'B'] sont symétriques par rapport à (D), alors :", opts: ["A'B' = 2 × AB", "A'B' < AB", "A'B' = AB", "A'B' > AB"], ans: 2, expl: "La symétrie conserve les longueurs : A'B' = AB.", part: "symetrie_segment" },
    { q: "Le symétrique d'un angle par rapport à une droite est :", opts: ["Un angle de mesure double", "Un angle de mesure moitié", "Un angle de même mesure", "Un segment"], ans: 2, expl: "La symétrie axiale conserve les angles. Le symétrique d'un angle a la même mesure.", part: "symetrie_segment" },
    { q: "Une figure a un axe de symétrie (∆) si :", opts: ["Chaque point de la figure est sur (∆)", "(∆) partage la figure en deux parties égales quelconques", "Chaque point de la figure a son symétrique par rapport à (∆) aussi dans la figure", "La figure est un carré"], ans: 2, expl: "Une figure a un axe de symétrie (∆) si et seulement si le symétrique de chaque point de la figure par rapport à (∆) appartient aussi à la figure.", part: "axe_symetrie" },
    { q: "Combien d'axes de symétrie possède un cercle ?", opts: ["1", "4", "0", "Une infinité"], ans: 3, expl: "Un cercle a une infinité d'axes de symétrie : tous ses diamètres sont des axes de symétrie.", part: "axe_symetrie" },
    { q: "Un segment a combien d'axe(s) de symétrie ?", opts: ["0", "1 (sa médiatrice)", "2", "Une infinité"], ans: 1, expl: "Un segment a exactement 1 axe de symétrie : sa médiatrice.", part: "axe_symetrie" },
    { q: "Si deux droites (D₁) et (D₂) sont parallèles, leurs symétriques par rapport à une droite (D) sont :", opts: ["Perpendiculaires entre elles", "Parallèles entre elles", "Confondues", "Sécantes"], ans: 1, expl: "Les symétriques de deux droites parallèles sont deux droites parallèles.", part: "prop_alignes" },
    { q: "La symétrie axiale conserve :", opts: ["Seulement les longueurs", "Seulement les angles", "Seulement l'alignement", "Les longueurs, les angles et l'alignement"], ans: 3, expl: "La symétrie axiale est une isométrie : elle conserve longueurs, angles et alignement.", part: "axe_symetrie" },
    { q: "Le symétrique d'un cercle de centre O par rapport à (D) est :", opts: ["Un cercle de centre différent et rayon différent", "Un cercle de même centre O", "Un cercle de même rayon et de centre O' (symétrique de O)", "Un disque"], ans: 2, expl: "Le symétrique d'un cercle (C) de centre O est un cercle de même rayon dont le centre est O', le symétrique de O.", part: "symetrie_segment" },
    { q: "Combien d'axes de symétrie a un triangle équilatéral ?", opts: ["0", "1", "2", "3"], ans: 3, expl: "Un triangle équilatéral a 3 axes de symétrie, qui sont ses trois médiatrices.", part: "axe_symetrie" },
    { q: "Combien d'axes de symétrie a un triangle isocèle (non équilatéral) ?", opts: ["0", "1", "2", "3"], ans: 1, expl: "Un triangle isocèle a exactement 1 axe de symétrie : la médiatrice de sa base.", part: "axe_symetrie" },
    { q: "Une droite a combien d'axes de symétrie ?", opts: ["0", "1", "2", "Une infinité"], ans: 3, expl: "Une droite a une infinité d'axes de symétrie : elle-même et toutes ses perpendiculaires.", part: "axe_symetrie" },
    { q: "Si M ∈ (D), alors son symétrique par rapport à (D) est :", opts: ["Le point M'", "Un point sur (D)", "M lui-même", "Le milieu de [MM']"], ans: 2, expl: "Si M ∈ (D), alors M est son propre symétrique : M' = M.", part: "def_symetrique" },
    { q: "Pour que A et A' soient symétriques par rapport à (D), il faut que (D) soit :", opts: ["Parallèle à [AA']", "Perpendiculaire à [AA'] en son milieu", "Sécante à [AA']", "Confondue avec [AA']"], ans: 1, expl: "(D) doit être à la fois perpendiculaire à [AA'] et passer par son milieu, i.e. être la médiatrice de [AA'].", part: "def_symetrique" },
    { q: "Combien d'axes de symétrie a un rectangle (non carré) ?", opts: ["0", "1", "2", "4"], ans: 2, expl: "Un rectangle a 2 axes de symétrie : les droites passant par les milieux des côtés opposés.", part: "axe_symetrie" },
    { q: "Le symétrique du milieu M d'un segment [AB] par rapport à (D) est :", opts: ["Le milieu de [AB]", "Le milieu du segment [A'B'] (symétriques de A et B)", "Un point quelconque", "Le centre de [A'B'] décalé"], ans: 1, expl: "Le symétrique du milieu d'un segment est le milieu du segment symétrique.", part: "symetrie_segment" },
    { q: "Les symétriques de deux droites perpendiculaires par rapport à une droite sont :", opts: ["Parallèles", "Obliques", "Perpendiculaires", "Confondues"], ans: 2, expl: "La symétrie conserve la perpendicularité : les symétriques de deux droites perpendiculaires sont perpendiculaires.", part: "prop_alignes" },
    { q: "Le nombre d'axes de symétrie d'un carré est :", opts: ["2", "3", "4", "8"], ans: 2, expl: "Un carré a 4 axes de symétrie : les 2 médiatrices des côtés et les 2 diagonales.", part: "axe_symetrie" },
    { q: "La symétrie axiale transforme une figure en une figure :", opts: ["Plus petite", "Plus grande", "Identique (superposable)", "Tournée de 90°"], ans: 2, expl: "La symétrie axiale est une isométrie : elle produit une figure superposable à l'originale.", part: "axe_symetrie" },
    { q: "Abena trace le symétrique d'un triangle par rapport à (D). La nature du triangle obtenu est :", opts: ["Différente du triangle original", "La même que le triangle original", "Toujours rectangle", "Toujours isocèle"], ans: 1, expl: "La symétrie conserve les longueurs et les angles, donc la nature du triangle est conservée.", part: "symetrie_segment" },
    { q: "Si (D) est l'axe de symétrie d'une figure (F), alors :", opts: ["Tous les points de (F) sont sur (D)", "Le symétrique de (F) par rapport à (D) est (F) elle-même", "La figure est un cercle", "La figure est symétrique par rapport à un point"], ans: 1, expl: "Si (D) est un axe de symétrie de (F), alors le symétrique de (F) par rapport à (D) est la figure (F) elle-même.", part: "axe_symetrie" },
    { q: "Un losange a combien d'axes de symétrie ?", opts: ["0", "1", "2", "4"], ans: 2, expl: "Un losange a 2 axes de symétrie : ses deux diagonales.", part: "axe_symetrie" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 4 — Angles
  // ─────────────────────────────────────────────────
  4: [
    { q: "Un angle AOB est formé par :", opts: ["Deux segments", "Deux demi-droites [OA) et [OB) de même sommet O", "Deux droites parallèles", "Un point et une droite"], ans: 1, expl: "Un angle est formé par deux demi-droites de même sommet. L'angle AOB a pour sommet O et pour côtés [OA) et [OB).", part: "presentation_angles" },
    { q: "L'unité de mesure d'angle la plus utilisée est :", opts: ["Le radian", "Le grade", "Le degré (°)", "Le centimètre"], ans: 2, expl: "L'unité de mesure d'angle la plus utilisée est le degré (°).", part: "presentation_angles" },
    { q: "Un angle aigu mesure :", opts: ["Exactement 90°", "Entre 90° et 180°", "Entre 0° et 90°", "180°"], ans: 2, expl: "Un angle aigu a une mesure comprise entre 0° et 90° (strictement).", part: "presentation_angles" },
    { q: "Un angle droit mesure :", opts: ["0°", "45°", "90°", "180°"], ans: 2, expl: "Un angle droit mesure exactement 90°.", part: "presentation_angles" },
    { q: "Un angle plat mesure :", opts: ["90°", "180°", "270°", "360°"], ans: 1, expl: "Un angle plat mesure 180°. Les deux côtés forment une droite.", part: "presentation_angles" },
    { q: "La bissectrice d'un angle AOB est la droite (OM) telle que :", opts: ["mes AOM = 90°", "mes AOM = mes MOB", "mes AOM = mes AOB", "OM est perpendiculaire à OB"], ans: 1, expl: "La bissectrice partage l'angle en deux angles de même mesure : mes AOM = mes MOB.", part: "presentation_angles" },
    { q: "Deux angles adjacents ont en commun :", opts: ["La même mesure", "Le même sommet et un côté commun", "Deux côtés communs", "La même bissectrice"], ans: 1, expl: "Deux angles adjacents ont le même sommet, un côté commun, et leurs autres côtés de part et d'autre.", part: "angles_adj" },
    { q: "Si les angles AOM et MOB sont adjacents, alors :", opts: ["mes AOM = mes MOB", "mes AOM + mes MOB = 90°", "mes AOM + mes MOB = mes AOB", "mes AOM × mes MOB = mes AOB"], ans: 2, expl: "Pour des angles adjacents : mes AOM + mes MOB = mes AOB.", part: "angles_adj" },
    { q: "Deux angles complémentaires ont une somme de mesures égale à :", opts: ["90°", "180°", "360°", "270°"], ans: 0, expl: "Deux angles complémentaires sont deux angles dont la somme des mesures est 90°.", part: "compl_suppl" },
    { q: "Un angle mesure 37°. Quel est son complémentaire ?", opts: ["143°", "53°", "323°", "127°"], ans: 1, expl: "Complémentaire = 90° − 37° = 53°.", part: "compl_suppl" },
    { q: "Deux angles supplémentaires ont une somme de mesures égale à :", opts: ["90°", "180°", "360°", "270°"], ans: 1, expl: "Deux angles supplémentaires sont deux angles dont la somme des mesures est 180°.", part: "compl_suppl" },
    { q: "Un angle mesure 107°. Quel est son supplémentaire ?", opts: ["73°", "253°", "83°", "17°"], ans: 0, expl: "Supplémentaire = 180° − 107° = 73°.", part: "compl_suppl" },
    { q: "Deux angles complémentaires tels que mes MNP = 53° et mes EFG = 37°. Que vaut leur somme ?", opts: ["90°", "180°", "16°", "80°"], ans: 0, expl: "53° + 37° = 90°. Les deux angles sont bien complémentaires.", part: "compl_suppl" },
    { q: "Deux angles EMN et KPC sont supplémentaires avec mes EMN = 35°. Calcule mes KPC.", opts: ["55°", "145°", "35°", "325°"], ans: 1, expl: "Supplémentaire : mes KPC = 180° − 35° = 145°.", part: "compl_suppl" },
    { q: "Deux angles opposés par le sommet sont des angles dont :", opts: ["Les côtés sont parallèles", "Les côtés de l'un sont des demi-droites opposées aux côtés de l'autre", "La somme est 90°", "Le sommet est différent"], ans: 1, expl: "Deux angles opposés par le sommet ont leurs côtés deux à deux sur des demi-droites opposées.", part: "angles_ops" },
    { q: "Deux angles opposés par le sommet ont :", opts: ["La même somme", "Des côtés perpendiculaires", "La même mesure", "Des mesures complémentaires"], ans: 2, expl: "Propriété : Deux angles opposés par le sommet ont la même mesure.", part: "angles_ops" },
    { q: "La somme des angles d'un triangle est :", opts: ["90°", "180°", "270°", "360°"], ans: 1, expl: "Dans un triangle, la somme des mesures des trois angles est toujours 180°.", part: "somme_triangle" },
    { q: "Dans un triangle ABC, mes A = 70° et mes B = 50°. Calcule mes C.", opts: ["120°", "60°", "130°", "40°"], ans: 1, expl: "mes C = 180° − 70° − 50° = 60°.", part: "somme_triangle" },
    { q: "Dans un triangle rectangle en A, les deux angles aigus sont :", opts: ["Supplémentaires", "Opposés par le sommet", "Complémentaires", "Adjacents"], ans: 2, expl: "Dans un triangle rectangle, les deux angles aigus sont complémentaires (leur somme = 90°).", part: "somme_triangle" },
    { q: "Dans un triangle rectangle en A avec mes B = 27°, quelle est la mesure de l'angle C ?", opts: ["153°", "63°", "27°", "90°"], ans: 1, expl: "Angle A = 90°, mes B = 27°. mes C = 180° − 90° − 27° = 63°.", part: "somme_triangle" },
    { q: "Un triangle équilatéral a des angles qui mesurent chacun :", opts: ["45°", "90°", "60°", "30°"], ans: 2, expl: "Dans un triangle équilatéral, les 3 angles ont la même mesure : 180° ÷ 3 = 60°.", part: "somme_triangle" },
    { q: "Un angle obtus mesure :", opts: ["Exactement 90°", "Entre 0° et 90°", "Entre 90° et 180°", "180°"], ans: 2, expl: "Un angle obtus a une mesure strictement comprise entre 90° et 180°.", part: "presentation_angles" },
    { q: "La mesure d'un angle nul (AOB où A = B) est :", opts: ["1°", "0°", "90°", "180°"], ans: 1, expl: "Un angle nul mesure 0°. Les deux demi-droites [OA) et [OB) sont confondues.", part: "presentation_angles" },
    { q: "Dans un triangle isocèle rectangle en D, quelle est la mesure de chaque angle aigu ?", opts: ["30°", "45°", "60°", "90°"], ans: 1, expl: "Angle droit = 90°. Les deux angles aigus sont égaux : (180° − 90°) ÷ 2 = 45°.", part: "somme_triangle" },
    { q: "Un angle mesure 17°. Son complémentaire mesure :", opts: ["17°", "163°", "73°", "107°"], ans: 2, expl: "Complémentaire = 90° − 17° = 73°.", part: "compl_suppl" },
    { q: "Si la droite (OM) est la bissectrice de l'angle AOB et mes AOB = 80°, alors mes AOM =", opts: ["80°", "40°", "160°", "20°"], ans: 1, expl: "La bissectrice partage l'angle en deux parties égales : mes AOM = 80° ÷ 2 = 40°.", part: "presentation_angles" },
    { q: "Les angles adjacents AOM et MOB ont mes AOM = 42° et mes AOB = 115°. Calcule mes MOB.", opts: ["73°", "57°", "157°", "42°"], ans: 0, expl: "mes MOB = mes AOB − mes AOM = 115° − 42° = 73°.", part: "angles_adj" },
    { q: "Deux angles sont supplémentaires et l'un mesure 120°. L'autre mesure :", opts: ["240°", "60°", "30°", "120°"], ans: 1, expl: "180° − 120° = 60°.", part: "compl_suppl" },
    { q: "Koné trace deux angles opposés par le sommet. L'un mesure 65°. L'autre mesure :", opts: ["115°", "25°", "65°", "295°"], ans: 2, expl: "Les angles opposés par le sommet sont de même mesure : 65°.", part: "angles_ops" },
    { q: "Dans un triangle DEF rectangle en E, si mes F = 36°, calcule mes D.", opts: ["54°", "144°", "36°", "90°"], ans: 0, expl: "Angle E = 90°. mes D = 180° − 90° − 36° = 54°.", part: "somme_triangle" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 5 — Nombres décimaux relatifs
  // ─────────────────────────────────────────────────
  5: [
    { q: "L'ensemble de tous les nombres entiers relatifs est noté :", opts: ["ℕ", "ℤ", "ℝ", "ℚ"], ans: 1, expl: "L'ensemble des nombres entiers relatifs (positifs, négatifs et zéro) est noté ℤ.", part: "ensemble_relatifs" },
    { q: "Le nombre 0 est à la fois :", opts: ["Positif seulement", "Négatif seulement", "Ni positif ni négatif", "Positif et négatif"], ans: 3, expl: "0 est le seul entier relatif à la fois positif et négatif.", part: "ensemble_relatifs" },
    { q: "Parmi ces nombres, lequel est un entier relatif négatif ?", opts: ["+6", "0", "−8", "+1"], ans: 2, expl: "−8 est un entier relatif négatif. +6 et +1 sont positifs, 0 est à la fois positif et négatif.", part: "ensemble_relatifs" },
    { q: "Tous les entiers naturels (ℕ) sont :", opts: ["Des entiers relatifs négatifs", "Des entiers relatifs positifs", "Des nombres décimaux seulement", "Ni positifs ni négatifs"], ans: 1, expl: "Tous les entiers naturels (0, 1, 2, …) sont des entiers relatifs positifs.", part: "ensemble_relatifs" },
    { q: "Sur un axe gradué, quel est le plus grand entre (+3,14) et (−5,7) ?", opts: ["−5,7", "+3,14", "Ils sont égaux", "On ne peut pas comparer"], ans: 1, expl: "Tout nombre positif est plus grand que tout nombre négatif. +3,14 > −5,7.", part: "ordre_relatifs" },
    { q: "Comment comparer deux entiers relatifs négatifs : −4,258 et −4,257 ?", opts: ["−4,258 > −4,257 car 258 > 257", "−4,257 > −4,258 car −4,258 a la plus grande valeur absolue", "−4,258 = −4,257", "On ne peut pas comparer"], ans: 1, expl: "Pour des négatifs, le plus grand est celui qui a la plus petite distance à zéro. |−4,257| < |−4,258|, donc −4,257 > −4,258.", part: "ordre_relatifs" },
    { q: "Calcule (−5) + (−3).", opts: ["+8", "−8", "+2", "−2"], ans: 1, expl: "Deux négatifs de même signe : on additionne les valeurs et on garde le signe. −5 + (−3) = −(5 + 3) = −8.", part: "somme_relatifs" },
    { q: "Calcule (+7) + (−3).", opts: ["+10", "−10", "+4", "−4"], ans: 2, expl: "Signes différents : on soustrait les valeurs absolues et on garde le signe du plus grand. 7 − 3 = 4, signe positif. Résultat : +4.", part: "somme_relatifs" },
    { q: "Calcule (−3,14) + (+5,7).", opts: ["−2,56", "+2,56", "−8,84", "+8,84"], ans: 1, expl: "|−3,14| = 3,14 ; |+5,7| = 5,7. Différence : 5,7 − 3,14 = 2,56. Signe du plus grand (5,7) : +. Résultat : +2,56.", part: "somme_relatifs" },
    { q: "Calcule (+9) − (−3,6).", opts: ["+5,4", "−12,6", "+12,6", "−5,4"], ans: 2, expl: "Soustraire un négatif revient à additionner : (+9) − (−3,6) = +9 + 3,6 = +12,6.", part: "difference_relatifs" },
    { q: "Calcule (−5) − (+3,6).", opts: ["−1,4", "+1,4", "−8,6", "+8,6"], ans: 2, expl: "(−5) − (+3,6) = −5 + (−3,6) = −(5 + 3,6) = −8,6.", part: "difference_relatifs" },
    { q: "Calcule (−11,3) − (−2,7).", opts: ["−14", "+14", "−8,6", "+8,6"], ans: 2, expl: "(−11,3) − (−2,7) = −11,3 + 2,7 = −(11,3 − 2,7) = −8,6.", part: "difference_relatifs" },
    { q: "Calcule (+4) × (−3) × (−1).", opts: ["+12", "−12", "+8", "−8"], ans: 0, expl: "(+4) × (−3) = −12, puis (−12) × (−1) = +12. Deux signes négatifs → positif.", part: "produit_relatifs" },
    { q: "Le produit de deux nombres de signes contraires est :", opts: ["Positif", "Négatif", "Nul", "Indéfini"], ans: 1, expl: "Le produit de deux nombres de signes contraires (l'un positif, l'autre négatif) est toujours négatif.", part: "produit_relatifs" },
    { q: "Le produit de deux nombres négatifs est :", opts: ["Toujours négatif", "Toujours positif", "Nul", "Peut être positif ou négatif"], ans: 1, expl: "Le produit de deux nombres négatifs est positif : (−a) × (−b) = +ab.", part: "produit_relatifs" },
    { q: "Calcule (−3)⁵.", opts: ["−243", "+243", "−15", "+15"], ans: 0, expl: "(−3)⁵ = −3 × −3 × −3 × −3 × −3. L'exposant est impair, donc le résultat est négatif : −243.", part: "produit_relatifs" },
    { q: "La puissance d'un nombre négatif à exposant pair est :", opts: ["Toujours négative", "Toujours positive", "Nulle", "Impossible"], ans: 1, expl: "Un nombre négatif à exposant pair est positif : (−a)² = a² > 0.", part: "produit_relatifs" },
    { q: "La solution de l'équation x + a = b est :", opts: ["x = a + b", "x = b − a", "x = b + a", "x = a − b"], ans: 1, expl: "L'équation x + a = b admet pour solution x = b − a.", part: "equation_relatifs" },
    { q: "Résous : x + (+5,4) = +7,3.", opts: ["x = +12,7", "x = +1,9", "x = −1,9", "x = −12,7"], ans: 1, expl: "x = 7,3 − 5,4 = +1,9.", part: "equation_relatifs" },
    { q: "Résous : x + (−3) = +5.", opts: ["x = +2", "x = +8", "x = −8", "x = −2"], ans: 1, expl: "x = +5 − (−3) = +5 + 3 = +8.", part: "equation_relatifs" },
    { q: "Calcule (−2,5) + 0.", opts: ["0", "−2,5", "+2,5", "+5"], ans: 1, expl: "Tout nombre additionné à 0 donne ce même nombre. (−2,5) + 0 = −2,5.", part: "somme_relatifs" },
    { q: "Compare (−6,321) et (−6,32).", opts: ["−6,321 > −6,32", "−6,321 = −6,32", "−6,321 < −6,32", "On ne peut pas comparer"], ans: 2, expl: "|−6,321| = 6,321 > 6,32 = |−6,32|, donc −6,321 < −6,32.", part: "ordre_relatifs" },
    { q: "Calcule (+4) × (−3) × (+1,5).", opts: ["−18", "+18", "−6", "+6"], ans: 0, expl: "+4 × −3 = −12, puis −12 × +1,5 = −18.", part: "produit_relatifs" },
    { q: "Calcule (−1)²⁰¹⁸.", opts: ["−1", "+1", "2018", "−2018"], ans: 1, expl: "(−1)^(pair) = +1. L'exposant 2018 est pair, donc (−1)²⁰¹⁸ = +1.", part: "produit_relatifs" },
    { q: "Calcule (−2)⁷.", opts: ["+128", "−128", "+14", "−14"], ans: 1, expl: "(−2)⁷ = −(2⁷) = −128 car l'exposant 7 est impair.", part: "produit_relatifs" },
    { q: "Résous : x + (−6) = +2.", opts: ["x = −8", "x = −4", "x = +8", "x = +4"], ans: 2, expl: "x = +2 − (−6) = +2 + 6 = +8.", part: "equation_relatifs" },
    { q: "Calcule (−7,5) + (+11,3) + (−2,7).", opts: ["+1,1", "−1,1", "+21,5", "−21,5"], ans: 0, expl: "(−7,5) + 11,3 = +3,8, puis 3,8 + (−2,7) = +1,1.", part: "somme_relatifs" },
    { q: "Quel est l'opposé de (−4,3) ?", opts: ["−4,3", "+4,3", "0", "+8,6"], ans: 1, expl: "L'opposé de (−4,3) est (+4,3). La somme d'un nombre et de son opposé vaut 0.", part: "ensemble_relatifs" },
    { q: "Calcule (−2) × (−2) × (−2) × (−2).", opts: ["−16", "+16", "−8", "+8"], ans: 1, expl: "(−2)⁴ = +(2⁴) = +16 car l'exposant est pair.", part: "produit_relatifs" },
    { q: "Aminata dépense 1 500 F et reçoit 3 200 F. En notant les dépenses comme négatifs, son solde est :", opts: ["+4 700 F", "+1 700 F", "−1 700 F", "−4 700 F"], ans: 1, expl: "(−1 500) + (+3 200) = +1 700 F. Aminata a un solde positif de 1 700 F.", part: "somme_relatifs" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 6 — Segments : Caractérisation & Médiatrice
  // ─────────────────────────────────────────────────
  6: [
    { q: "Si M appartient au segment [AB], quelle relation vérifie-t-on ?", opts: ["AM − MB = AB", "AM + MB = AB", "AM × MB = AB", "AM = MB"], ans: 1, expl: "Propriété 1 : Si M ∈ [AB], alors AM + MB = AB.", part: "carac_segment" },
    { q: "On donne M ∈ [AB], AB = 7,4 cm et MB = 3,2 cm. Calcule AM.", opts: ["4,2 cm", "10,6 cm", "2,3 cm", "4,6 cm"], ans: 0, expl: "AM = AB − MB = 7,4 − 3,2 = 4,2 cm.", part: "carac_segment" },
    { q: "Si M ∈ [AB] et AM = 2 cm, MB = 3,7 cm, alors AB vaut :", opts: ["1,7 cm", "5,7 cm", "7,4 cm", "3 cm"], ans: 1, expl: "AB = AM + MB = 2 + 3,7 = 5,7 cm.", part: "carac_segment" },
    { q: "O ∈ [IJ]. On peut écrire :", opts: ["IO − OJ = IJ", "IO + OJ = IJ", "IO = OJ", "IO × OJ = IJ"], ans: 1, expl: "Si O ∈ [IJ], alors IO + OJ = IJ.", part: "carac_segment" },
    { q: "Si AM + MB = AB, que peut-on conclure ?", opts: ["A est entre M et B", "M est entre A et B (M appartient à [AB])", "M est à l'extérieur de [AB]", "Les trois points sont en triangle"], ans: 1, expl: "Propriété réciproque : Si AM + MB = AB, alors M ∈ [AB] (M est entre A et B).", part: "reciproque_segment" },
    { q: "AB = 8 cm, AE = 5 cm, EB = 4 cm. E appartient-il à [AB] ?", opts: ["Oui, car 5 + 4 = 8", "Non, car AE + EB = 9 ≠ 8", "On ne peut pas savoir", "Oui, car AE < AB"], ans: 1, expl: "AE + EB = 5 + 4 = 9 ≠ 8 = AB, donc E n'appartient pas à [AB].", part: "reciproque_segment" },
    { q: "BM = 7,5 cm et AM = 3 cm. Si M ∈ [AB], alors AB vaut :", opts: ["4,5 cm", "7,5 cm", "10,5 cm", "3 cm"], ans: 2, expl: "AB = AM + MB = 3 + 7,5 = 10,5 cm.", part: "carac_segment" },
    { q: "Si M appartient à la médiatrice d'un segment [AB], alors :", opts: ["MA > MB", "MA < MB", "MA = MB", "M est le milieu de [AB]"], ans: 2, expl: "Propriété 1 de la médiatrice : Si M ∈ médiatrice de [AB], alors MA = MB.", part: "carac_mediatrice" },
    { q: "La médiatrice d'un segment [AB] est la droite qui :", opts: ["Passe par A et B", "Est perpendiculaire à [AB] et passe par son milieu", "Est parallèle à [AB]", "Passe par A perpendiculairement"], ans: 1, expl: "La médiatrice de [AB] passe par le milieu de [AB] et est perpendiculaire à (AB).", part: "carac_mediatrice" },
    { q: "La droite (∆) est la médiatrice de [EF]. Un point K ∈ (∆) vérifie KE = 6,5 cm. Alors KF vaut :", opts: ["13 cm", "3,25 cm", "6,5 cm", "0 cm"], ans: 2, expl: "K ∈ médiatrice de [EF] → KF = KE = 6,5 cm.", part: "carac_mediatrice" },
    { q: "Si MA = MB, que peut-on conclure ?", opts: ["M est le milieu de [AB]", "M appartient à la médiatrice de [AB]", "M appartient à [AB]", "M est à l'extérieur de [AB]"], ans: 1, expl: "Propriété réciproque : Si MA = MB, alors M appartient à la médiatrice de [AB].", part: "reciproque_mediatrice" },
    { q: "IM = IN = 7 cm et JM = JN = 4,5 cm. La droite (IJ) est :", opts: ["La médiane de [MN]", "La médiatrice de [MN]", "La hauteur de [MN]", "La bissectrice de l'angle MN"], ans: 1, expl: "IM = IN donc I ∈ médiatrice de [MN]. JM = JN donc J ∈ médiatrice de [MN]. (IJ) est la médiatrice de [MN].", part: "reciproque_mediatrice" },
    { q: "Un point M est équidistant de A et B. Cela signifie :", opts: ["MA + MB = AB", "M est le milieu de [AB]", "MA = MB", "M est sur [AB]"], ans: 2, expl: "Un point équidistant de A et B vérifie MA = MB. Il appartient à la médiatrice de [AB].", part: "carac_mediatrice" },
    { q: "EF = 130,2 mm, N ∈ [EF] et NF = 57,9 mm. Calcule EN.", opts: ["188,1 mm", "72,3 mm", "57,9 mm", "65,1 mm"], ans: 1, expl: "EN = EF − NF = 130,2 − 57,9 = 72,3 mm.", part: "carac_segment" },
    { q: "Pour AB = 5 cm, AM = 2 cm, MB = 3 cm. M ∈ [AB] ?", opts: ["Non, car 2 + 3 ≠ 5", "Oui, car 2 + 3 = 5", "On ne peut pas savoir", "Non, car AM ≠ MB"], ans: 1, expl: "AM + MB = 2 + 3 = 5 = AB, donc M ∈ [AB].", part: "reciproque_segment" },
    { q: "Pour AB = 4 cm, AM = 3 cm, MB = 7 cm. M ∈ [AB] ?", opts: ["Oui", "Non, car AM + MB = 10 ≠ 4", "Oui, car AM < AB", "On ne peut pas savoir"], ans: 1, expl: "AM + MB = 3 + 7 = 10 ≠ 4, donc M n'appartient pas à [AB].", part: "reciproque_segment" },
    { q: "Le cercle de centre O passant par F et P. O appartient à :", opts: ["La droite (FP)", "La médiatrice de [FP]", "Le milieu de [FP]", "La tangente en F"], ans: 1, expl: "OA = OB = OC (rayon), donc O est équidistant de F et P, donc O ∈ médiatrice de [FP].", part: "reciproque_mediatrice" },
    { q: "On donne AS = 6,5 cm. (D) est la médiatrice de [AC]. Si S ∈ (D), alors SC vaut :", opts: ["13 cm", "3,25 cm", "6,5 cm", "0 cm"], ans: 2, expl: "S ∈ médiatrice de [AC] → SA = SC = 6,5 cm.", part: "carac_mediatrice" },
    { q: "Quelle est la propriété réciproque de la caractérisation d'un segment ?", opts: ["Si M ∈ [AB], alors AM + MB = AB", "Si AM + MB = AB, alors M ∈ [AB]", "Si AM = MB, alors M ∈ [AB]", "Si M ∈ [AB], alors AM = MB"], ans: 1, expl: "Propriété réciproque : Si AM + MB = AB, alors M ∈ [AB].", part: "reciproque_segment" },
    { q: "Pour AB = 9 cm, AM = MB = 4,5 cm. M ∈ [AB] ?", opts: ["Oui, car AM + MB = 9 = AB", "Non, car AM = MB", "Non, car 4,5 + 4,5 ≠ 9", "On ne peut pas savoir"], ans: 0, expl: "AM + MB = 4,5 + 4,5 = 9 = AB, donc M ∈ [AB]. M est même le milieu de [AB].", part: "reciproque_segment" },
    { q: "Sur la médiatrice de [AB], les points sont :", opts: ["Plus proches de A que de B", "Plus proches de B que de A", "Équidistants de A et de B", "Confondus avec A"], ans: 2, expl: "Par définition de la médiatrice, tout point de la médiatrice est équidistant de A et B.", part: "carac_mediatrice" },
    { q: "La médiatrice d'un segment passe par :", opts: ["L'un des sommets seulement", "Un point quelconque", "Le milieu du segment", "L'extrémité du segment"], ans: 2, expl: "La médiatrice passe par le milieu du segment et est perpendiculaire à ce segment.", part: "carac_mediatrice" },
    { q: "Konan mesure MA = 4 cm et MB = 4 cm. Il en déduit que M est sur la médiatrice de [AB]. Cette déduction est :", opts: ["Fausse, car MA = MB ne suffit pas", "Vraie, car MA = MB implique M ∈ médiatrice de [AB]", "Vraie seulement si M est le milieu", "Fausse, car M doit être entre A et B"], ans: 1, expl: "C'est la propriété réciproque de la médiatrice : MA = MB ⟹ M ∈ médiatrice de [AB].", part: "reciproque_mediatrice" },
    { q: "Si AB = 8 cm et AF = 6 cm et FB = 2 cm, alors F ∈ [AB] ?", opts: ["Non, car AF ≠ FB", "Oui, car AF + FB = 8 = AB", "Non, car AF > FB", "On ne peut pas savoir"], ans: 1, expl: "AF + FB = 6 + 2 = 8 = AB, donc F ∈ [AB].", part: "reciproque_segment" },
    { q: "Pour construire la médiatrice d'un segment, on utilise :", opts: ["Un rapporteur seulement", "La règle seule", "Un compas et une règle", "Un crayon et de la colle"], ans: 2, expl: "On construit la médiatrice en traçant deux cercles de même rayon depuis chaque extrémité et en reliant les intersections.", part: "carac_mediatrice" },
    { q: "M est un point de [AB] tel que AM = MB. M est :", opts: ["Un point extérieur à [AB]", "Le milieu de [AB]", "Un point quelconque de [AB]", "Le point de [AB] le plus proche de A"], ans: 1, expl: "Si M ∈ [AB] et AM = MB, alors M est le milieu de [AB].", part: "carac_segment" },
    { q: "Sur la figure, (D) est la médiatrice du segment [BC] et BK = 3,4 cm. Alors KC vaut :", opts: ["6,8 cm", "1,7 cm", "3,4 cm", "0 cm"], ans: 2, expl: "K ∈ (D) = médiatrice de [BC] → KB = KC = 3,4 cm.", part: "carac_mediatrice" },
    { q: "AB + BM = AM signifie que :", opts: ["M ∈ [AB]", "A ∈ [AB] tel que A entre B et M", "B ∈ [AM] (B est entre A et M)", "A est le milieu de [BM]"], ans: 2, expl: "AB + BM = AM indique que B est entre A et M, donc B ∈ [AM].", part: "carac_segment" },
    { q: "Dans un triangle ABC, (IJ) passe par deux points I et J tels que IA = IB et JA = JB. (IJ) est :", opts: ["La hauteur de [AB]", "La médiatrice de [AB]", "La médiane de [AB]", "La bissectrice de [AB]"], ans: 1, expl: "IA = IB → I ∈ médiatrice de [AB]. JA = JB → J ∈ médiatrice de [AB]. Donc (IJ) est la médiatrice de [AB].", part: "reciproque_mediatrice" },
    { q: "Si AB = 3 cm, AM = MB = 3 cm, M ∈ [AB] ?", opts: ["Oui, car 3 + 3 = 6 > 3", "Non, car AM + MB = 6 ≠ 3", "Oui, car AM = MB", "On ne peut pas savoir"], ans: 1, expl: "AM + MB = 3 + 3 = 6 ≠ 3 = AB. Donc M ∉ [AB].", part: "reciproque_segment" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 7 — Fractions
  // ─────────────────────────────────────────────────
  7: [
    { q: "Calcule 3/7 + 5/7.", opts: ["8/14", "8/7", "2/7", "15/49"], ans: 1, expl: "Même dénominateur : a/d + b/d = (a+b)/d. 3/7 + 5/7 = (3+5)/7 = 8/7.", part: "somme_meme_denom" },
    { q: "Calcule 19/13 − 6/13.", opts: ["25/13", "13/26", "13/13", "13/26"], ans: 2, expl: "19/13 − 6/13 = (19−6)/13 = 13/13 = 1.", part: "somme_meme_denom" },
    { q: "Calcule 18/11 + 4/11.", opts: ["22/22", "22/11", "14/11", "2"], ans: 1, expl: "18/11 + 4/11 = (18+4)/11 = 22/11 = 2.", part: "somme_meme_denom" },
    { q: "Pour additionner 4/7 et 1/5, on réduit au même dénominateur. Le dénominateur commun est :", opts: ["7", "5", "12", "35"], ans: 3, expl: "Le dénominateur commun de 7 et 5 est leur produit 7 × 5 = 35.", part: "somme_diff_denom" },
    { q: "Calcule 4/7 + 1/5.", opts: ["5/12", "27/35", "5/35", "4/35"], ans: 1, expl: "4/7 + 1/5 = (4×5)/(35) + (1×7)/(35) = 20/35 + 7/35 = 27/35.", part: "somme_diff_denom" },
    { q: "Calcule 8/3 + 7/6.", opts: ["15/9", "23/6", "1/6", "15/6"], ans: 1, expl: "8/3 = 16/6. 16/6 + 7/6 = 23/6.", part: "somme_diff_denom" },
    { q: "Calcule 9/10 + 11/15.", opts: ["20/25", "47/30", "20/150", "3/2"], ans: 1, expl: "PPCM(10,15)=30. 9/10=27/30, 11/15=22/30. 27/30+22/30=49/30.", part: "somme_diff_denom" },
    { q: "Calcule 4/7 − 1/5.", opts: ["3/2", "13/35", "20/35", "3/35"], ans: 1, expl: "4/7 − 1/5 = 20/35 − 7/35 = 13/35.", part: "somme_diff_denom" },
    { q: "Calcule 2 + 1/13.", opts: ["3/13", "27/13", "2/13", "26/13"], ans: 1, expl: "2 = 26/13. Donc 2 + 1/13 = 26/13 + 1/13 = 27/13.", part: "somme_diff_denom" },
    { q: "Calcule (11/5) × 4.", opts: ["44/5", "11/20", "44/20", "15/5"], ans: 0, expl: "k × (a/b) = ka/b. (11/5) × 4 = (11 × 4)/5 = 44/5.", part: "produit_fraction" },
    { q: "Calcule 9 × 7/12.", opts: ["63/12", "16/12", "63/108", "7/4"], ans: 0, expl: "9 × 7/12 = (9 × 7)/12 = 63/12 = 21/4.", part: "produit_fraction" },
    { q: "Calcule (7/5) × (9/4).", opts: ["63/20", "16/9", "63/9", "28/45"], ans: 0, expl: "(a/b) × (c/d) = (a×c)/(b×d). (7×9)/(5×4) = 63/20.", part: "produit_fraction" },
    { q: "Calcule (49/15) × (9/14).", opts: ["441/210", "21/10", "63/29", "3/10"], ans: 1, expl: "(49 × 9)/(15 × 14) = 441/210. Simplifions : 441/210 = 63/30 = 21/10.", part: "produit_fraction" },
    { q: "Comment s'écrit (2/5)⁴ développé ?", opts: ["2/5 + 2/5 + 2/5 + 2/5", "(2/5) × (2/5) × (2/5) × (2/5)", "2⁴/5", "2/5⁴"], ans: 1, expl: "(2/5)⁴ = (2/5) × (2/5) × (2/5) × (2/5). C'est le produit de 4 facteurs égaux à 2/5.", part: "puissance_fraction" },
    { q: "Calcule (2/3)⁴.", opts: ["8/12", "16/81", "8/81", "2/81"], ans: 1, expl: "(2/3)⁴ = 2⁴/3⁴ = 16/81.", part: "puissance_fraction" },
    { q: "Calcule (4/5)².", opts: ["8/10", "16/25", "8/25", "16/10"], ans: 1, expl: "(4/5)² = 4²/5² = 16/25.", part: "puissance_fraction" },
    { q: "Calcule (1/2)⁷.", opts: ["7/2", "1/14", "1/128", "1/64"], ans: 2, expl: "(1/2)⁷ = 1⁷/2⁷ = 1/128.", part: "puissance_fraction" },
    { q: "Pour encadrer 47/19, on effectue :", opts: ["47 × 19", "47 ÷ 19 puis on encadre le résultat", "19 ÷ 47", "47 − 19"], ans: 1, expl: "On divise le numérateur par le dénominateur : 47 ÷ 19 ≈ 2,47. On encadre selon le nombre de décimales demandé.", part: "encadrement_fraction" },
    { q: "47/19 ≈ 2,47368... Encadre 47/19 par deux entiers consécutifs.", opts: ["1 < 47/19 < 2", "2 < 47/19 < 3", "3 < 47/19 < 4", "47/19 est un entier"], ans: 1, expl: "2,47... est entre 2 et 3 : 2 < 47/19 < 3.", part: "encadrement_fraction" },
    { q: "47/19 ≈ 2,47368. Encadre à l'ordre 2 (2 chiffres après la virgule).", opts: ["2,47 < 47/19 < 2,48", "2,4 < 47/19 < 2,5", "2 < 47/19 < 3", "2,473 < 47/19 < 2,474"], ans: 0, expl: "À l'ordre 2 : on prend 2,47 et on ajoute 0,01 pour la borne sup : 2,47 < 47/19 < 2,48.", part: "encadrement_fraction" },
    { q: "Pour réduire 4/7 et 1/5 au même dénominateur, 4/7 devient :", opts: ["4/35", "20/35", "4/5", "12/35"], ans: 1, expl: "4/7 = (4 × 5)/(7 × 5) = 20/35.", part: "somme_diff_denom" },
    { q: "Calcule 6/5 − 4/7.", opts: ["2/2", "22/35", "10/35", "42/35"], ans: 1, expl: "6/5 = 42/35, 4/7 = 20/35. 42/35 − 20/35 = 22/35.", part: "somme_diff_denom" },
    { q: "La règle du produit de deux fractions est :", opts: ["a/b + c/d = (a+c)/(b+d)", "a/b × c/d = (a+c)/(b×d)", "a/b × c/d = (a×c)/(b×d)", "a/b × c/d = (a×d)/(b×c)"], ans: 2, expl: "Le produit de deux fractions : (a/b) × (c/d) = (a × c) / (b × d).", part: "produit_fraction" },
    { q: "Calcule (3/4)².", opts: ["9/16", "6/8", "9/8", "3/16"], ans: 0, expl: "(3/4)² = 3²/4² = 9/16.", part: "puissance_fraction" },
    { q: "5/7 encadrée à l'ordre 3 : 5 ÷ 7 ≈ 0,714... Quelle est l'encadrement correct ?", opts: ["0,71 < 5/7 < 0,72", "0,714 < 5/7 < 0,715", "0,7 < 5/7 < 0,8", "0,714 < 5/7 < 0,716"], ans: 1, expl: "À l'ordre 3 : 0,714 < 5/7 < 0,715.", part: "encadrement_fraction" },
    { q: "Calcule 2 − 1/13.", opts: ["1/13", "25/13", "27/13", "−24/13"], ans: 1, expl: "2 = 26/13. 26/13 − 1/13 = 25/13.", part: "somme_diff_denom" },
    { q: "Calcule 9/10 − 11/15.", opts: ["−2/5", "47/30", "1/30", "3/2"], ans: 2, expl: "9/10=27/30, 11/15=22/30. 27/30 − 22/30 = 5/30 = 1/6. Attention : 1/6 = 5/30. Vérifions : 1/30 non, 5/30=1/6.", part: "somme_diff_denom" },
    { q: "Calcule 18/5 − 4/5.", opts: ["14/5", "14/10", "22/5", "0"], ans: 0, expl: "(18 − 4)/5 = 14/5.", part: "somme_meme_denom" },
    { q: "Calcule 6/13 − 4/13.", opts: ["10/13", "2/26", "2/13", "10/26"], ans: 2, expl: "(6 − 4)/13 = 2/13.", part: "somme_meme_denom" },
    { q: "Calcule (7/5) × (4/9).", opts: ["28/45", "11/14", "63/20", "28/14"], ans: 0, expl: "(7 × 4)/(5 × 9) = 28/45.", part: "produit_fraction" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 8 — Triangles
  // ─────────────────────────────────────────────────
  8: [
    { q: "Un triangle ABC a combien de sommets ?", opts: ["2", "3", "4", "6"], ans: 1, expl: "Un triangle a 3 sommets, 3 côtés et 3 angles.", part: "triangle_vocab" },
    { q: "Dans un triangle ABC, le côté opposé au sommet A est :", opts: ["[AB]", "[AC]", "[BC]", "[CA]"], ans: 2, expl: "Le côté opposé à un sommet est le côté qui n'a pas ce sommet comme extrémité. Le côté opposé à A est [BC].", part: "triangle_vocab" },
    { q: "Un triangle isocèle est un triangle qui :", opts: ["A trois côtés de même longueur", "A un angle droit", "A deux côtés de même longueur", "A tous les angles égaux"], ans: 2, expl: "Un triangle isocèle est un triangle qui a deux côtés de même longueur.", part: "triangle_isocele" },
    { q: "Dans un triangle isocèle en A, AB = AC. La base du triangle est :", opts: ["[AB]", "[AC]", "[BC]", "La médiatrice"], ans: 2, expl: "Dans un triangle isocèle en A, les deux côtés égaux sont [AB] et [AC]. La base est le côté différent : [BC].", part: "triangle_isocele" },
    { q: "Dans un triangle isocèle en A, mes ABC = mes ACB. Cette propriété s'appelle :", opts: ["Côtés égaux", "Angles à la base égaux", "Angle au sommet", "Médiatrice de base"], ans: 1, expl: "Dans un triangle isocèle, les angles à la base ont la même mesure.", part: "triangle_isocele" },
    { q: "L'axe de symétrie d'un triangle isocèle est :", opts: ["La médiane du sommet principal", "La médiatrice de la base", "La hauteur de n'importe quel côté", "La bissectrice d'un angle quelconque"], ans: 1, expl: "La médiatrice de la base est l'axe de symétrie du triangle isocèle.", part: "triangle_isocele" },
    { q: "Un triangle équilatéral est un triangle qui :", opts: ["A un angle droit", "A deux côtés égaux", "A trois côtés égaux", "A trois angles différents"], ans: 2, expl: "Un triangle équilatéral a ses trois côtés de même longueur.", part: "triangle_equilateral" },
    { q: "Chaque angle d'un triangle équilatéral mesure :", opts: ["30°", "45°", "60°", "90°"], ans: 2, expl: "Somme des angles = 180°. Angles égaux donc 180°/3 = 60° chacun.", part: "triangle_equilateral" },
    { q: "Un triangle équilatéral a combien d'axes de symétrie ?", opts: ["1", "2", "3", "0"], ans: 2, expl: "Un triangle équilatéral a 3 axes de symétrie (ses 3 médiatrices).", part: "triangle_equilateral" },
    { q: "Un triangle rectangle est un triangle qui :", opts: ["A tous les côtés égaux", "A deux côtés égaux", "A un angle droit", "A un angle obtus"], ans: 2, expl: "Un triangle rectangle est un triangle qui possède un angle droit (90°).", part: "triangle_rectangle" },
    { q: "Dans un triangle rectangle, le côté le plus long s'appelle :", opts: ["La médiane", "L'hypoténuse", "Le sommet", "La hauteur"], ans: 1, expl: "Dans un triangle rectangle, le côté opposé à l'angle droit est l'hypoténuse, et c'est le plus long côté.", part: "triangle_rectangle" },
    { q: "ABC est triangle rectangle en B. Les deux angles aigus sont :", opts: ["Supplémentaires", "Complémentaires", "Opposés par le sommet", "Adjacents et égaux"], ans: 1, expl: "Les deux angles aigus d'un triangle rectangle sont complémentaires (leur somme = 90°).", part: "triangle_rectangle" },
    { q: "EFG est rectangle en F, avec mes G = 36°. Calcule mes E.", opts: ["54°", "144°", "36°", "90°"], ans: 0, expl: "mes E + mes G = 90° → mes E = 90° − 36° = 54°.", part: "triangle_rectangle" },
    { q: "La médiatrice d'un côté d'un triangle est la droite qui :", opts: ["Passe par les 3 sommets", "Passe par un sommet et est perpendiculaire au côté opposé", "Passe par le milieu du côté et est perpendiculaire à ce côté", "Partage un angle en deux"], ans: 2, expl: "La médiatrice d'un segment passe par son milieu et lui est perpendiculaire.", part: "droites_particulieres" },
    { q: "Les trois médiatrices d'un triangle sont concourantes en :", opts: ["L'orthocentre", "Le centre de gravité", "Le centre du cercle circonscrit", "L'incentre"], ans: 2, expl: "Les trois médiatrices d'un triangle sont concourantes au centre du cercle circonscrit.", part: "droites_particulieres" },
    { q: "Une hauteur d'un triangle est :", opts: ["La droite passant par un sommet et le milieu du côté opposé", "La droite passant par un sommet perpendiculairement au côté opposé", "La médiatrice d'un côté", "La bissectrice d'un angle"], ans: 1, expl: "Une hauteur est la droite passant par un sommet et perpendiculaire au côté opposé.", part: "droites_particulieres" },
    { q: "L'orthocentre d'un triangle est le point de concours des :", opts: ["Trois médiatrices", "Trois médianes", "Trois hauteurs", "Trois bissectrices"], ans: 2, expl: "Les trois hauteurs d'un triangle sont concourantes en un point appelé orthocentre.", part: "droites_particulieres" },
    { q: "Une médiane d'un triangle est :", opts: ["La droite passant par un sommet et perpendiculaire au côté opposé", "La droite passant par un sommet et le milieu du côté opposé", "La médiatrice d'un côté", "La bissectrice d'un angle"], ans: 1, expl: "Une médiane passe par un sommet et le milieu du côté opposé.", part: "droites_particulieres" },
    { q: "Le centre de gravité est le point de concours des :", opts: ["Trois médiatrices", "Trois médianes", "Trois hauteurs", "Trois bissectrices"], ans: 1, expl: "Les trois médianes d'un triangle se coupent au centre de gravité.", part: "droites_particulieres" },
    { q: "Les bissectrices d'un triangle sont concourantes en :", opts: ["L'orthocentre", "Le centre du cercle inscrit", "Le centre du cercle circonscrit", "Le centre de gravité"], ans: 1, expl: "Les trois bissectrices se coupent au centre du cercle inscrit dans le triangle.", part: "droites_particulieres" },
    { q: "Dans tout triangle, la longueur d'un côté est :", opts: ["Égale à la somme des deux autres", "Supérieure à la somme des deux autres", "Inférieure à la somme des deux autres côtés", "Le double de la moyenne des deux autres"], ans: 2, expl: "Inégalité triangulaire : AB < AC + CB (et de même pour les autres côtés).", part: "inegalites_triangul" },
    { q: "Peut-on construire un triangle de côtés 3, 7 et 4 cm ?", opts: ["Oui", "Non, car 3 + 4 = 7 (non strictement inférieur)", "Non, car 7 > 4", "On ne peut pas savoir"], ans: 1, expl: "Il faut que chaque côté < somme des deux autres. 3 + 4 = 7 (pas strictement inférieur), donc pas de triangle.", part: "inegalites_triangul" },
    { q: "Peut-on construire un triangle de côtés 2, 7 et 4 cm ?", opts: ["Oui, car 2 + 7 > 4", "Non, car 2 + 4 = 6 < 7", "Oui, car 4 + 2 > 7", "On ne peut pas savoir"], ans: 1, expl: "2 + 4 = 6 < 7, donc l'inégalité triangulaire n'est pas respectée.", part: "inegalites_triangul" },
    { q: "Les points E, F, G tels que EF = 6, FG = 5, EG = 4. Forment-ils un triangle ?", opts: ["Non", "Oui, car 4 + 5 = 9 > 6, 5 + 6 = 11 > 4, 4 + 6 = 10 > 5", "Non, car il faut des côtés entiers", "Oui, mais seulement si rectangle"], ans: 1, expl: "On vérifie les 3 inégalités : 4+5>6 ✓, 5+6>4 ✓, 4+6>5 ✓. C'est un triangle.", part: "inegalites_triangul" },
    { q: "Un triangle isocèle avec un angle au sommet de 60° est :", opts: ["Rectangle", "Obtusangle", "Équilatéral", "Quelconque"], ans: 2, expl: "Si un triangle isocèle a son angle au sommet = 60°, les angles à la base valent (180°−60°)/2 = 60°. Donc équilatéral.", part: "triangle_isocele" },
    { q: "Si un triangle a deux angles de même mesure (mes B = mes C = 67°), c'est :", opts: ["Un triangle équilatéral", "Un triangle isocèle", "Un triangle rectangle", "Un triangle quelconque"], ans: 1, expl: "Si deux angles sont égaux, les côtés opposés sont égaux : c'est un triangle isocèle.", part: "triangle_isocele" },
    { q: "Combien de médianes a un triangle ?", opts: ["1", "2", "3", "4"], ans: 2, expl: "Un triangle a exactement 3 médianes (une par sommet).", part: "droites_particulieres" },
    { q: "Pour construire un triangle ABC avec AB = 7, AC = 4, BC = 5 cm, on utilise :", opts: ["Un rapporteur", "Une règle seule", "Un compas et une règle", "Seulement un compas"], ans: 2, expl: "On trace un côté, puis deux cercles de rayons correspondants aux autres côtés pour trouver le 3ème sommet.", part: "triangle_vocab" },
    { q: "Un triangle peut-il avoir deux angles droits ?", opts: ["Oui", "Non, car la somme des angles serait ≥ 180°", "Oui, si les côtés sont très longs", "Oui, si le triangle est isocèle"], ans: 1, expl: "La somme des angles = 180°. Deux angles droits = 180°, il ne resterait rien pour le 3ème angle.", part: "triangle_vocab" },
    { q: "ABC est rectangle en A. Le cercle de diamètre [BC] :", opts: ["Passe par les milieux des côtés", "Passe par A", "Est inscrit dans ABC", "A son centre en A"], ans: 1, expl: "Si le triangle est rectangle en A, alors A appartient au cercle de diamètre [BC].", part: "triangle_rectangle" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 9 — Cercles et disques
  // ─────────────────────────────────────────────────
  9: [
    { q: "Comment note-t-on un cercle de centre O et de rayon r ?", opts: ["D(O ; r)", "C(O ; r)", "S(O ; r)", "T(O ; r)"], ans: 1, expl: "Un cercle de centre O et de rayon r se note C(O ; r) ou (C).", part: "cercle_disque" },
    { q: "Comment note-t-on un disque de centre O et de rayon r ?", opts: ["C(O ; r)", "D(O ; r)", "S(O ; r)", "T(O ; r)"], ans: 1, expl: "Un disque de centre O et de rayon r se note D(O ; r).", part: "cercle_disque" },
    { q: "Quelle est la différence entre un cercle et un disque ?", opts: ["Aucune différence", "Le cercle est la ligne courbe, le disque inclut l'intérieur", "Le disque est plus grand", "Le disque n'a pas de rayon"], ans: 1, expl: "Le cercle est la courbe (ligne), le disque est la surface délimitée (cercle + intérieur).", part: "cercle_disque" },
    { q: "Si OM < r, le point M est :", opts: ["Sur le cercle", "À l'extérieur du cercle", "À l'intérieur du cercle", "Au centre du cercle"], ans: 2, expl: "Si OM < r, le point M est à l'intérieur du cercle (C) de centre O et de rayon r.", part: "positions_cercle" },
    { q: "Si OM = r, le point M est :", opts: ["À l'intérieur du cercle", "À l'extérieur du cercle", "Sur le cercle", "Au centre"], ans: 2, expl: "Si OM = r, alors M appartient au cercle (C).", part: "positions_cercle" },
    { q: "Si OM > r, le point M est :", opts: ["Sur le cercle", "À l'intérieur du cercle", "À l'extérieur du cercle", "Au centre"], ans: 2, expl: "Si OM > r, le point M est à l'extérieur du cercle (C).", part: "positions_cercle" },
    { q: "Cercle (C) de centre O et rayon 3 cm. OM = 4 cm. M est :", opts: ["Sur (C)", "À l'intérieur de (C)", "À l'extérieur de (C)", "Au centre"], ans: 2, expl: "OM = 4 > r = 3, donc M est à l'extérieur de (C).", part: "positions_cercle" },
    { q: "Cercle (C) de centre O et rayon 3 cm. OM = 2 cm. M est :", opts: ["Sur (C)", "À l'intérieur de (C)", "À l'extérieur de (C)", "Au centre"], ans: 1, expl: "OM = 2 < r = 3, donc M est à l'intérieur de (C).", part: "positions_cercle" },
    { q: "Un point M appartient au disque D(O ; r) si :", opts: ["OM > r", "OM = r seulement", "OM < r ou OM = r", "OM < r seulement"], ans: 2, expl: "M ∈ D(O ; r) si OM ≤ r, c'est-à-dire OM < r (intérieur) ou OM = r (sur le cercle).", part: "carac_disque" },
    { q: "Le disque D(A ; 4 cm) contient-il un point M tel que AM = 4 cm ?", opts: ["Non, car M serait sur le cercle", "Oui, car AM = r et M ∈ D(A ; 4)", "Non, car M doit être à l'intérieur", "On ne peut pas savoir"], ans: 1, expl: "M ∈ D(A ; r) si AM ≤ r. AM = r = 4, donc M est sur le cercle, qui appartient au disque.", part: "carac_disque" },
    { q: "Le cercle circonscrit à un triangle est le cercle qui :", opts: ["Est à l'intérieur du triangle", "Passe par les trois sommets du triangle", "Passe par les milieux des côtés", "A son centre au milieu d'un côté"], ans: 1, expl: "Le cercle circonscrit à un triangle passe par ses trois sommets.", part: "cercle_circonscrit" },
    { q: "Le centre du cercle circonscrit à un triangle est :", opts: ["Le centre de gravité", "L'orthocentre", "L'intersection des médiatrices des côtés", "Le milieu du plus grand côté"], ans: 2, expl: "Les médiatrices des côtés sont concourantes au centre du cercle circonscrit.", part: "cercle_circonscrit" },
    { q: "Si O est le centre du cercle circonscrit à ABC, alors :", opts: ["OA = OB uniquement", "OA = OB = OC (rayon du cercle)", "OA + OB = OC", "O est le milieu de [AC]"], ans: 1, expl: "O est équidistant des trois sommets : OA = OB = OC = rayon du cercle.", part: "cercle_circonscrit" },
    { q: "Le cercle inscrit dans un triangle est le cercle qui :", opts: ["Passe par les trois sommets", "Est tangent aux trois côtés (intérieur)", "Passe par les milieux des côtés", "A son centre à l'orthocentre"], ans: 1, expl: "Le cercle inscrit est à l'intérieur du triangle et tangent à chacun des trois côtés.", part: "cercle_inscrit" },
    { q: "Le centre du cercle inscrit dans un triangle est :", opts: ["L'intersection des médiatrices", "L'intersection des médianes", "L'intersection des hauteurs", "L'intersection des bissectrices"], ans: 3, expl: "Les trois bissectrices d'un triangle se coupent en un point qui est le centre du cercle inscrit.", part: "cercle_inscrit" },
    { q: "Aminata place un point S tel que IS = 6 cm par rapport au cercle (C) de centre I et rayon 5 cm. S est :", opts: ["Sur (C)", "À l'intérieur de (C)", "À l'extérieur de (C)", "Au centre de (C)"], ans: 2, expl: "IS = 6 > r = 5, donc S est à l'extérieur de (C).", part: "positions_cercle" },
    { q: "Un disque D(O ; r) comprend :", opts: ["Uniquement le cercle", "Uniquement l'intérieur du cercle", "Le cercle et son intérieur", "L'extérieur du cercle"], ans: 2, expl: "Le disque est l'ensemble des points à distance ≤ r du centre, soit l'intérieur et le cercle lui-même.", part: "carac_disque" },
    { q: "Trace le cercle (C) de centre O, rayon 3 cm. Pour AM = 4 cm, le point M est :", opts: ["Sur (C)", "Intérieur à (C)", "Extérieur à (C)", "Impossible"], ans: 2, expl: "OM = 4 > 3 = r, donc M est à l'extérieur.", part: "positions_cercle" },
    { q: "Pour construire le cercle inscrit dans un triangle, on trace d'abord :", opts: ["Les trois médiatrices", "Les trois médianes", "Les trois hauteurs", "Les trois bissectrices"], ans: 3, expl: "Le centre du cercle inscrit est l'intersection des trois bissectrices.", part: "cercle_inscrit" },
    { q: "OA = OB = OC = 5 cm. O est le centre du cercle :", opts: ["De rayon 15 cm", "De rayon 10 cm", "De rayon 5 cm passant par A, B et C", "D'aire 5 cm"], ans: 2, expl: "OA = OB = OC = r, donc r = 5 cm et le cercle passe par A, B et C.", part: "cercle_circonscrit" },
    { q: "D(A ; 4 cm) contient-il un point P tel que AP = 2 cm ?", opts: ["Non, car AP < r", "Oui, car AP = 2 < r = 4", "Non, car AP doit être égal à r", "On ne peut pas savoir"], ans: 1, expl: "AP = 2 < r = 4, donc P est à l'intérieur du disque, donc P ∈ D(A ; 4).", part: "carac_disque" },
    { q: "La médiatrice de [FP] passe par O si :", opts: ["OF < OP", "OF > OP", "OF = OP", "FP = r"], ans: 2, expl: "Un point appartient à la médiatrice si et seulement si il est équidistant des extrémités. OF = OP → O ∈ médiatrice de [FP].", part: "cercle_circonscrit" },
    { q: "Cercle (C) de rayon r = 4 cm. Un point M tel que OM = 4 cm : quelle est sa position ?", opts: ["Intérieur", "Extérieur", "Sur le cercle", "Au centre"], ans: 2, expl: "OM = r = 4 cm, donc M est sur le cercle (C).", part: "positions_cercle" },
    { q: "Pour construire le cercle circonscrit à un triangle PQR, on trace :", opts: ["Les 3 hauteurs", "Les 3 médianes", "Les 3 bissectrices", "Les 3 médiatrices des côtés"], ans: 3, expl: "Le centre du cercle circonscrit est l'intersection des 3 médiatrices des côtés.", part: "cercle_circonscrit" },
    { q: "Un point M ∈ disque D(O ; r) vérifie :", opts: ["OM > r", "OM = r uniquement", "OM ≤ r", "OM ≥ r"], ans: 2, expl: "M ∈ D(O ; r) ⟺ OM ≤ r (intérieur ou sur le cercle).", part: "carac_disque" },
    { q: "Si le point A est sur le cercle (C) de diamètre [BC], alors le triangle ABC est :", opts: ["Isocèle en A", "Équilatéral", "Rectangle en A", "Rectangle en B"], ans: 2, expl: "Si A est sur le cercle de diamètre [BC], alors l'angle en A est droit : ABC rectangle en A.", part: "cercle_inscrit" },
    { q: "Le rayon d'un cercle est :", opts: ["Le double du diamètre", "La moitié du diamètre", "Égal au diamètre", "L'aire divisée par π"], ans: 1, expl: "Le rayon r est la moitié du diamètre d : r = d/2.", part: "cercle_disque" },
    { q: "Note le cercle de centre I et de rayon 5 dm.", opts: ["D(I ; 5 dm)", "C(I ; 5 dm) ou C(I ; 5)", "S(I ; 5 dm)", "T(5 ; I dm)"], ans: 1, expl: "Notation : C(I ; r). Donc le cercle de centre I et rayon 5 dm se note C(I ; 5 dm).", part: "cercle_disque" },
    { q: "Cercle (C) de centre O. Si M ∈ (C), alors OM = :", opts: ["0", "r/2", "2r", "r"], ans: 3, expl: "Par définition, si M appartient au cercle (C) de centre O et de rayon r, alors OM = r.", part: "positions_cercle" },
    { q: "Kofi construit un cercle de rayon 3 cm. Il place le point P tel que OP = 3 cm. P est :", opts: ["Intérieur au cercle", "Extérieur au cercle", "Sur le cercle", "Au centre"], ans: 2, expl: "OP = r = 3 cm, donc P est sur le cercle.", part: "positions_cercle" },
  ],

  // ─────────────────────────────────────────────────
  // LEÇON 10 — Parallélogrammes, Proportionnalité, Statistiques, Prismes
  // ─────────────────────────────────────────────────
  10: [
    { q: "Un parallélogramme est un quadrilatère dont :", opts: ["Les diagonales sont égales", "Les côtés opposés sont parallèles", "Tous les angles sont droits", "Les côtés sont tous égaux"], ans: 1, expl: "Un parallélogramme est un quadrilatère dont les supports des côtés opposés sont parallèles.", part: "parallelogramme" },
    { q: "Dans un parallélogramme ABCD, les côtés opposés sont :", opts: ["Perpendiculaires", "De longueur différente", "De même longueur", "Toujours égaux et perpendiculaires"], ans: 2, expl: "Dans un parallélogramme, les côtés opposés ont la même longueur : AB = DC et AD = BC.", part: "parallelogramme" },
    { q: "Dans un parallélogramme, les diagonales se coupent :", opts: ["En angle droit", "En leurs tiers", "En leur milieu", "À l'extérieur du parallélogramme"], ans: 2, expl: "Dans un parallélogramme, les diagonales se coupent en leur milieu.", part: "parallelogramme" },
    { q: "Dans un parallélogramme ABCD, les angles de sommets consécutifs A et B sont :", opts: ["Complémentaires (somme 90°)", "Supplémentaires (somme 180°)", "Égaux", "Opposés par le sommet"], ans: 1, expl: "Dans un parallélogramme, deux angles consécutifs sont supplémentaires : mes A + mes B = 180°.", part: "parallelogramme" },
    { q: "Un rectangle est un parallélogramme qui a :", opts: ["Tous les côtés égaux", "Ses diagonales perpendiculaires", "Ses quatre angles droits", "Un seul angle droit"], ans: 2, expl: "Un rectangle est un quadrilatère qui a ses quatre angles droits.", part: "rectangle" },
    { q: "Dans un rectangle, les diagonales sont :", opts: ["Perpendiculaires", "De longueur différente", "De même longueur", "Absentes"], ans: 2, expl: "Propriété : Dans un rectangle, les diagonales ont la même longueur. AC = BD.", part: "rectangle" },
    { q: "EFGH est un rectangle avec EF = 7 cm et KM = 8 cm (diagonale). EG (autre diagonale) vaut :", opts: ["8 cm", "14 cm", "7 cm", "√(7²+8²) cm"], ans: 0, expl: "Dans un rectangle, les diagonales sont de même longueur. EG = FH = 8 cm.", part: "rectangle" },
    { q: "Un parallélogramme qui a un angle droit est :", opts: ["Un losange", "Un carré", "Un rectangle", "Un trapèze"], ans: 2, expl: "Un parallélogramme avec un angle droit est un rectangle (car tous les angles deviennent droits).", part: "rectangle" },
    { q: "Un losange est un quadrilatère qui a :", opts: ["Tous les angles droits", "Ses quatre côtés de même longueur", "Ses diagonales égales", "Deux paires de côtés parallèles seulement"], ans: 1, expl: "Un losange est un quadrilatère dont les quatre côtés ont la même longueur.", part: "losange" },
    { q: "Dans un losange, les diagonales sont :", opts: ["Égales", "Perpendiculaires", "Parallèles", "Absentes"], ans: 1, expl: "Propriété : Dans un losange, les supports des diagonales sont perpendiculaires.", part: "losange" },
    { q: "Un carré est à la fois :", opts: ["Un losange et un parallélogramme", "Un rectangle et un losange", "Un rectangle et un triangle", "Un losange et un cercle"], ans: 1, expl: "Un carré est à la fois un rectangle (4 angles droits) et un losange (4 côtés égaux).", part: "carre" },
    { q: "Un carré KLMN a KL = 5 cm. Toutes ses arêtes mesurent :", opts: ["10 cm", "5 cm", "20 cm", "25 cm"], ans: 1, expl: "Un carré a ses quatre côtés de même longueur. KL = LM = MN = NK = 5 cm.", part: "carre" },
    { q: "Dans un carré, les diagonales sont :", opts: ["Seulement perpendiculaires", "Seulement de même longueur", "Perpendiculaires ET de même longueur", "Ni perpendiculaires ni égales"], ans: 2, expl: "Dans un carré, les diagonales sont égales (propriété du rectangle) et perpendiculaires (propriété du losange).", part: "carre" },
    { q: "RSTU est un rectangle avec ST = TU. RSTU est :", opts: ["Un parallélogramme quelconque", "Un losange", "Un carré", "Un trapèze"], ans: 2, expl: "Un rectangle dont deux côtés consécutifs sont égaux (ST = TU) est un carré.", part: "carre" },
    { q: "Dans une étude statistique, la population est :", opts: ["Un seul individu étudié", "L'ensemble des objets ou êtres de l'étude", "Le nombre total d'individus", "Une modalité de l'étude"], ans: 1, expl: "La population est l'ensemble d'objets ou d'êtres sur lequel porte l'étude statistique.", part: "statistiques" },
    { q: "La fréquence d'une modalité est :", opts: ["L'effectif de la modalité", "(Effectif modalité / Effectif total) × 100", "L'effectif total / 100", "L'effectif total"], ans: 1, expl: "Fréquence (%) = (effectif de la modalité × 100) / effectif total.", part: "statistiques" },
    { q: "Dans une classe de 30 élèves, 9 ont 12 ans. La fréquence de la modalité « 12 ans » est :", opts: ["9 %", "30 %", "21 %", "12 %"], ans: 1, expl: "Fréquence = (9 / 30) × 100 = 30 %.", part: "statistiques" },
    { q: "Un caractère étudié qui est un nombre (ex : âge, taille) est dit :", opts: ["Qualitatif", "Quantitatif", "Fréquentiel", "Modal"], ans: 1, expl: "Un caractère qui peut prendre des valeurs numériques est dit quantitatif.", part: "statistiques" },
    { q: "Un caractère qui n'est pas un nombre (ex : marque de voiture) est dit :", opts: ["Quantitatif", "Fréquentiel", "Qualitatif", "Statistique"], ans: 2, expl: "Un caractère non numérique est dit qualitatif.", part: "statistiques" },
    { q: "Un prisme droit est un solide dont les faces latérales sont :", opts: ["Des triangles", "Des cercles", "Des rectangles", "Des losanges"], ans: 2, expl: "Les faces latérales d'un prisme droit sont des rectangles.", part: "prismes" },
    { q: "L'aire latérale d'un prisme droit de périmètre de base P et de hauteur h est :", opts: ["A = 2 × P × h", "A = P × h", "A = P + h", "A = B × h"], ans: 1, expl: "L'aire latérale d'un prisme droit : A = P × h (périmètre de la base × hauteur).", part: "prismes" },
    { q: "Le volume d'un prisme droit est V = :", opts: ["P × h", "2B + Ph", "B + h", "B × h"], ans: 3, expl: "Volume d'un prisme droit : V = B × h, où B est l'aire d'une base et h la hauteur.", part: "prismes" },
    { q: "Prisme droit avec P = 21 dm et h = 6 dm. L'aire latérale vaut :", opts: ["27 dm²", "126 dm²", "63 dm²", "42 dm²"], ans: 1, expl: "A = P × h = 21 × 6 = 126 dm².", part: "prismes" },
    { q: "Prisme droit avec B = 12,5 m² et h = 4 m. Son volume est :", opts: ["16,5 m³", "50 m³", "8,5 m³", "48 m³"], ans: 1, expl: "V = B × h = 12,5 × 4 = 50 m³.", part: "prismes" },
    { q: "L'aire totale d'un prisme droit est :", opts: ["At = A + B", "At = A × 2B", "At = A + 2B", "At = P × h + B"], ans: 2, expl: "At = A + 2B (aire latérale + 2 fois l'aire d'une base).", part: "prismes" },
    { q: "Un parallélogramme ABCD a mes A = 70°. La mesure de l'angle B est :", opts: ["70°", "110°", "140°", "90°"], ans: 1, expl: "Dans un parallélogramme, deux angles consécutifs sont supplémentaires : mes B = 180° − 70° = 110°.", part: "parallelogramme" },
    { q: "Un quadrilatère dont les diagonales se coupent en leur milieu est :", opts: ["Un rectangle", "Un losange", "Un carré", "Un parallélogramme"], ans: 3, expl: "Un quadrilatère dont les diagonales se coupent en leur milieu est un parallélogramme.", part: "parallelogramme" },
    { q: "ABCD est un losange de côté c = 5 cm. Son périmètre est :", opts: ["10 cm", "15 cm", "20 cm", "25 cm"], ans: 2, expl: "Périmètre du losange P = 4 × c = 4 × 5 = 20 cm.", part: "losange" },
    { q: "Losange ABCD avec AC = 8 cm et BD = 6 cm. Son aire est :", opts: ["48 cm²", "24 cm²", "14 cm²", "12 cm²"], ans: 1, expl: "Aire du losange A = (a × b) / 2 = (8 × 6) / 2 = 24 cm².", part: "losange" },
    { q: "Dans un tableau de proportionnalité, si on représente les couples (x, y) dans un repère, les points sont :", opts: ["Dispersés aléatoirement", "Formant un cercle", "Alignés sur une droite passant par l'origine", "Tous sur l'axe des abscisses"], ans: 2, expl: "Les points d'un tableau de proportionnalité sont alignés sur une droite passant par l'origine du repère.", part: "statistiques" },
  ],
};
